### ISSUE TITLE
No files at Git

### ISSUE THREAD

**Issue by zmisik** [ComForth/WebApiKendoAngular#1]
Hi Andris,

There is no files on the git...please send the project to GIT...

Thanks,
Your friendly codeing partner (z)

**Comment by sosandris** [comment]
Neeeeem tudom hogy kelll

----- Eredeti üzenet -----
Feladó: "zmisik" <notifications@github.com>
Feladva: ‎2016.‎02.‎04. 13:28
Címzett: "ComForth/WebApiKendoAngular" <WebApiKendoAngular@noreply.github.com>
Tárgy: [WebApiKendoAngular] No files at Git (#1)

Hi Andris,
There is no files on the gitplease send the project to GIT
Thanks,
Your friendly codeing partner (z)

**Comment by sosandris** [comment]
fent van juhúúú
